Mention Friston's idea of Markov Blankets as Boundaries
Vulcan-Academy/Vulcanomicon pull request #73
Opened 2019-06-11 14:32 UTC by SeverTopan

Resolves #68

2019-06-11 21:25 UTC, macterra requested changes

2019-06-11 21:25 UTC, macterra commented on _lexicon/actor-boundary.md
> +Neuroscientist Karl Friston [suggests](https://www.wired.com/story/karl-friston-free-energy-principle-artificial-intelligence/) that the distinguishing surface between an __Actor__ and its __Environm
Suggest Markov be capitalized

2019-06-13 20:20 UTC, macterra approved these changes

2019-06-18 15:55 UTC, cecilyth approved these changes

2019-07-01 03:38 UTC, merged